#!/usr/bin/env bash
cont=$(buildah from ros)
echo $cont

buildah run "$cont" -- apt update
buildah run "$cont" -- apt upgrade -y

buildah run "$cont" -- apt install python3 git nano pip tmux ffmpeg libsm6 libxext6 ros-humble-cv-bridge ros-humble-image-pipeline ros-humble-foxglove-msgs ros-humble-rqt-image-overlay-layer -y
#buildan run "$cont" -- apt install ros-humble-rqt* ros-humble-foxglove-bridge -y
#buildan run "$cont" -- apt install rviz2 x11vnc xvfb -y

buildah add "$cont" . '/workspace'

buildah run "$cont" -- echo "source /workspace/install.setup.bash" >> ~/.bashrc
buildah run "$cont" -- echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc

buildah config --workingdir /workspace "$cont"
buildah config --cmd "bash" "$cont"

buildah run "$cont" -- pip install -r requirements.txt

#Rust Ros2
#buildah run "$cont" -- curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
#buildah run "$cont" -- apt install -y git libclang-dev python3-pip python3-vcstool # libclang-dev is required by bindgen
#buildah run "$cont" -- cargo install --debug cargo-ament-build  # --debug is faster to install
#buildah run "$cont" -- pip install git+https://github.com/colcon/colcon-cargo.git
#buildah run "$cont" -- pip install git+https://github.com/colcon/colcon-ros-cargo.git

#Rust Opencv
#buildah run "$cont" -- apt install -y libopencv-dev clang libclang-dev

## Commit this container to an image name
buildah commit "$cont" ros

